---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
provisioner:
  name: chef_solo
  client_rb:
    audit_mode: :enabled

platforms:
  - name: centos-7.4
    run_list:
      - recipe[chef-openshift::default]

suites:
  - name: openshift
    driver:
      vm_hostname: "openshift-lab.aws.internal"
